version: '3.8'

services:
  obfuscator:
    image: ghcr.io/vasie1337/obfuscator:latest
    volumes:
      - obfuscator-data:/data
    # The default command from the Dockerfile (obfuscator --help) will be used.
    # You can override it here if needed, e.g.:
    command: ["input.exe", "-o", "output.exe"]

volumes:
  obfuscator-data: 